// Code generated by Suga SDK generator. DO NOT EDIT.

package com.example.helloworldapi;

import com.addsuga.client.SugaClient;

import com.addsuga.client.Bucket;


/**
 * Generated client provides access to suga application resources
 */
public class GeneratedSugaClient extends SugaClient {
    
    private final Bucket image;
    

    public GeneratedSugaClient() {
        super();
        
        this.image = createBucket("image");
        
    }

    public GeneratedSugaClient(String address) {
        super(address);
        
        this.image = createBucket("image");
        
    }
    

    public Bucket getImage() {
        return this.image;
    }
    
}