# Code generated by Suga SDK generator. DO NOT EDIT.

import os
import grpc
from suga.gen.storage.v2 import storage_pb2_grpc

from suga.buckets import Bucket


class SugaClient:
    def __init__(self):
        address = os.getenv("SUGA_SERVICE_ADDRESS")
        if not address:
            address = "localhost:50051"
        
        self._channel = grpc.insecure_channel(address)
        
        self._storage_client = storage_pb2_grpc.StorageStub(self._channel)
        
        
        
        self.files = Bucket(self._storage_client, "files")
        

    def close(self):
        self._channel.close()

