// Code generated by Suga SDK generator. DO NOT EDIT.

package com.example.helloworldapi

import com.addsuga.client.SugaClient

import com.addsuga.client.Bucket


/**
 * Generated client provides access to suga application resources
 */
class GeneratedSugaClient : SugaClient {
    
    val image: Bucket
    

    constructor() : super() {
        
        this.image = createBucket("image")
        
    }

    constructor(address: String) : super(address) {
        
        this.image = createBucket("image")
        
    }
}